import Head from "next/head";

import { Hero, About, Skills, Projects, Contact } from "../components";

export default function Home() {
  return (
    <div>
      <Head>
        <title>NextJS Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <About />
      <Skills />
      <Projects />
      <Contact />
    </div>
  );
}
